package app.playlist;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClient;
import org.springframework.web.util.UriComponentsBuilder;

import java.net.URI;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Component
public class SpotifyClient {

    private static final Logger logger = LoggerFactory.getLogger(SpotifyClient.class);

    private final RestClient restClient;
    private final ObjectMapper objectMapper = new ObjectMapper();

    public SpotifyClient(RestClient.Builder builder) {
        this.restClient = builder.build();
    }

    public Optional<String> searchTrackUri(TrackSuggestion suggestion, String authHeader) {
        try {
            URI uri = UriComponentsBuilder.fromUriString("https://api.spotify.com/v1/search")
                .queryParam("q", "track:" + suggestion.track() + " artist:" + suggestion.artist())
                .queryParam("type", "track")
                .queryParam("limit", "1")
                .build()
                .encode()
                .toUri();

            String response = restClient.get()
                .uri(uri)
                .header("Authorization", authHeader)
                .retrieve()
                .body(String.class);

            JsonNode items = objectMapper.readTree(response).path("tracks").path("items");
            if (items.isArray() && !items.isEmpty()) {
                return Optional.of(items.get(0).path("uri").asText());
            }
            logger.warn("No Spotify result for: {} by {}", suggestion.track(), suggestion.artist());
            return Optional.empty();
        } catch (Exception e) {
            logger.warn("Spotify search failed for: {} by {} — {}", suggestion.track(), suggestion.artist(), e.getMessage());
            return Optional.empty();
        }
    }

    public String getUserId(String authHeader) {
        String response = restClient.get()
            .uri("https://api.spotify.com/v1/me")
            .header("Authorization", authHeader)
            .retrieve()
            .body(String.class);

        try {
            return objectMapper.readTree(response).path("id").asText();
        } catch (Exception e) {
            throw new RuntimeException("Failed to get Spotify user ID", e);
        }
    }

    public String createPlaylist(String userId, String prompt, String authHeader) {
        Map<String, String> body = Map.of(
            "name", "AI: " + prompt,
            "description", "Generated by AI for: " + prompt
        );

        String response = restClient.post()
            .uri("https://api.spotify.com/v1/users/" + userId + "/playlists")
            .header("Authorization", authHeader)
            .contentType(MediaType.APPLICATION_JSON)
            .body(body)
            .retrieve()
            .body(String.class);

        try {
            return objectMapper.readTree(response).path("id").asText();
        } catch (Exception e) {
            throw new RuntimeException("Failed to create Spotify playlist", e);
        }
    }

    public void addTracks(String playlistId, List<String> uris, String authHeader) {
        for (int i = 0; i < uris.size(); i += 100) {
            List<String> batch = uris.subList(i, Math.min(i + 100, uris.size()));
            restClient.post()
                .uri("https://api.spotify.com/v1/playlists/" + playlistId + "/tracks")
                .header("Authorization", authHeader)
                .contentType(MediaType.APPLICATION_JSON)
                .body(Map.of("uris", batch))
                .retrieve()
                .toBodilessEntity();
        }
    }
}